<script lang="ts">
    import {onMount} from 'svelte';
    import {base} from '$app/paths';
    import {identity,account,loadIdentity} from '$lib/identity';
    let error=$state(''), notice=$state(''), busy=$state(false), name=$state(''), invite=$state(''), invitation=$state(''), inviteRole=$state('editor'), label=$state(''), tokenRole=$state('editor'), newToken=$state('');
    let members=$state<{id:string;name:string;role:string}[]>([]), tokens=$state<{id:string;label:string;workspace:string;permission:string;expires_at:number}[]>([]);
    const current=$derived($identity.workspaces?.find(w=>w.id===$identity.workspace));
    const roleName=(role:string)=>({owner:'所有者',editor:'编辑者',viewer:'查看者'}[role]||role);
    async function refresh(){await loadIdentity();if($identity.enabled&&$identity.user){members=(await account('members')).members;tokens=(await account('tokens')).tokens;}}
    onMount(()=>{void refresh().catch(e=>error=e.message);});
    async function run(fn:()=>Promise<void>){busy=true;error='';notice='';try{await fn();}catch(e){error=e instanceof Error?e.message:String(e);}finally{busy=false;}}
    async function switchSpace(workspace:string){await account('switch',{workspace});location.replace(`${base}/writer`);}
    async function copy(value:string){await navigator.clipboard.writeText(value);notice='已复制，请通过你信任的方式分享或保存。';}
</script>
<svelte:head><title>账户与空间 · Vestige</title></svelte:head>
<main class="account-page">
    <header><div><span class="eyebrow">VESTIGE · 身份与协作</span><h1>账户与空间</h1><p>私人创作有自己的边界，共同创作有清晰的权限。</p></div>{#if $identity.user}<button disabled={busy} onclick={()=>run(async()=>{await account('logout');location.replace(`${base}/login`);})}>退出登录</button>{/if}</header>
    {#if error}<p class="error" role="alert">{error}</p>{/if}{#if notice}<p class="notice" role="status">{notice}</p>{/if}
    {#if !$identity.enabled}<section class="panel"><h2>当前使用本地单用户模式</h2><p>服务尚未配置统一登录。配置 KX 身份服务后，可使用私人空间、团队成员管理和个人 Agent 凭据。</p><a href={`${base}/writer`}>返回编剧工作台 →</a></section>
    {:else if $identity.user}
    <div class="identity"><strong>{$identity.user.name}</strong><span>KX 用户 {$identity.user.subject}</span><span>当前：{current?.name} · {roleName($identity.role||'')}</span></div>
    <div class="columns"><section class="panel"><h2>我的空间</h2><p>每个空间的记忆、文件和角色独立保存。</p><div class="spaces">{#each $identity.workspaces||[] as space}<button class:active={space.id===$identity.workspace} disabled={busy} onclick={()=>run(()=>switchSpace(space.id))}><span><strong>{space.name}</strong><small>{space.kind==='shared'?'团队共享':space.kind==='legacy'?'原有资料':'私人空间'} · {roleName(space.role)}</small></span><span>{space.id===$identity.workspace?'当前':'进入 →'}</span></button>{/each}</div>
    <form onsubmit={e=>{e.preventDefault();void run(async()=>{const r=await account('create_workspace',{name});await switchSpace(r.workspace);});}}><label>新建共享空间<input bind:value={name} required maxlength="120" placeholder="例如：短剧编剧共创组" /></label><button disabled={busy} class="primary">创建共享空间</button></form>
    <form onsubmit={e=>{e.preventDefault();void run(async()=>{const r=await account('join',{invitation:invite.trim()});await switchSpace(r.workspace);});}}><label>接受邀请<input bind:value={invite} required autocomplete="off" placeholder="粘贴一次性邀请码" /></label><button disabled={busy}>加入共享空间</button></form></section>
    <section class="panel"><h2>{current?.name}的成员</h2><p>编辑者可上传、对话和提交候选规则；所有者负责发布、回滚及角色删除。</p><div class="members">{#each members as member}<div class="row"><span><strong>{member.name}</strong><small>{roleName(member.role)}{member.id===$identity.user?.id?' · 我':''}</small></span>{#if $identity.role==='owner'&&member.role!=='owner'}<div class="actions"><select aria-label={`${member.name}的权限`} value={member.role} disabled={busy} onchange={e=>run(async()=>{await account('set_member',{user_id:member.id,role:e.currentTarget.value});await refresh();})}><option value="editor">编辑者</option><option value="viewer">查看者</option></select><button disabled={busy} onclick={()=>run(async()=>{await account('remove_member',{user_id:member.id});await refresh();})}>移除</button></div>{/if}</div>{/each}</div>
    {#if current?.kind==='shared'&&$identity.role==='owner'}<label>邀请权限<select bind:value={inviteRole}><option value="editor">编辑者 · 共同培养</option><option value="viewer">查看者 · 阅读与检索</option></select></label><button disabled={busy} onclick={()=>run(async()=>{invitation=(await account('invite',{role:inviteRole})).invitation;})}>生成一次性邀请码</button>{#if invitation}<div class="secret"><code>{invitation}</code><button onclick={()=>run(()=>copy(invitation))}>复制邀请码</button><small>24 小时内有效，仅能使用一次。加入后可访问该空间的全部资料。</small></div>{/if}
    {:else if current?.kind==='personal'}<p class="hint">私人空间不能邀请成员。共同培养角色时，请先创建共享空间。</p>{/if}</section></div>
    <section class="panel"><h2>Agent 访问凭据</h2><p>凭据绑定你的身份和当前空间，权限不会超过你的成员权限。上游登录失效或凭据撤销后，Agent 无法继续访问。</p><form class="token-form" onsubmit={e=>{e.preventDefault();void run(async()=>{newToken=(await account('create_token',{label,role:$identity.role==='viewer'?'viewer':tokenRole})).token;label='';await refresh();});}}><label>凭据名称<input bind:value={label} required maxlength="120" placeholder="例如：我的编剧 Agent" /></label><label>访问权限<select bind:value={tokenRole} disabled={$identity.role==='viewer'}><option value="viewer">查看与检索</option>{#if $identity.role!=='viewer'}<option value="editor">编辑与培养</option>{/if}</select></label><button disabled={busy} class="primary">创建凭据</button></form>
    {#if newToken}<div class="secret"><b>请现在保存，完整凭据仅显示一次。</b><code>{newToken}</code><button onclick={()=>run(()=>copy(newToken))}>复制凭据</button><small>MCP 地址：{typeof location!=='undefined'?location.origin:''}/mcp；使用 Authorization: Bearer 传入凭据。有效期不超过当前登录会话（最长 8 小时）。</small></div>{/if}
    <div class="tokens">{#each tokens as token}<div class="row"><span><strong>{token.label}</strong><small>{$identity.workspaces?.find(w=>w.id===token.workspace)?.name||'已退出的空间'} · {roleName(token.permission)} · 到期 {new Date(token.expires_at*1000).toLocaleString('zh-CN')}</small></span><button disabled={busy} onclick={()=>run(async()=>{await account('revoke_token',{id:token.id});newToken='';await refresh();})}>撤销</button></div>{/each}{#if !tokens.length}<p class="hint">尚未创建 Agent 凭据。</p>{/if}</div></section>
    {/if}
</main>
<style>
.account-page{height:100%;overflow:auto;background:radial-gradient(ellipse at 90% 0,#21362b55,transparent 50%),#0b130f;color:#d7e2d2;padding:35px 40px 60px max(30px,var(--os-content-left,0px));font-family:system-ui,sans-serif}header{display:flex;justify-content:space-between;gap:24px;align-items:center;margin-bottom:28px}.eyebrow{font-size:10px;letter-spacing:.2em;color:#aab998}h1{font-size:30px;margin:12px 0}h2{font-size:18px;margin:0 0 12px}p{color:#9daf9f;font-size:12px;line-height:1.8}.identity{display:flex;flex-wrap:wrap;gap:15px;padding:17px 0 25px;font-size:12px;color:#b7c6ad}.identity strong{color:#e4ebd4}.columns{display:grid;grid-template-columns:1fr 1fr;gap:22px}.panel{border:1px solid #344f38;background:#14201999;border-radius:12px;padding:25px;margin-bottom:24px;min-width:0}.spaces{display:grid;gap:10px}.spaces button{text-align:left;display:flex;justify-content:space-between;gap:12px;padding:15px}.spaces .active{border-color:#a4b572;background:#55643533}small{display:block;color:#90a087;font-size:10px;line-height:1.8;margin-top:6px}button,input,select{font:inherit;font-size:12px;border:1px solid #496448;border-radius:6px;padding:10px;background:#16271b;color:#ccddbf}button{cursor:pointer;white-space:nowrap}button:disabled{opacity:.5;cursor:not-allowed}button:hover{border-color:#a8bc86}input,select{width:100%;box-sizing:border-box;background:#0b170e}.primary{background:#bcc986;color:#182515}form{display:grid;gap:12px;margin-top:26px}label{display:grid;gap:9px;font-size:11px;color:#becbb2}.row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:18px 0;border-bottom:1px solid #304333;font-size:12px}.actions{display:flex;gap:8px;flex-shrink:0}.actions select{min-width:85px}.members{margin:18px 0}.panel>button{margin-top:14px}.token-form{grid-template-columns:1fr 180px auto;align-items:end}.secret{display:grid;gap:12px;padding:20px;background:#43552b33;border:1px solid #728848;border-radius:8px;margin-top:20px;font-size:12px}.secret code{overflow-wrap:anywhere;font-size:11px}.secret button{justify-self:start}.error,.notice{padding:14px;border-radius:8px}.error{color:#ebb8a7;background:#7b372f33}.notice{color:#c9e9b0;background:#335d2833}.hint{padding:15px 0}a{color:#b5cc89}@media(max-width:1000px){.columns{grid-template-columns:1fr}.token-form{grid-template-columns:1fr}}@media(max-width:767px){.account-page{padding:25px 18px 95px}.panel{padding:20px}.row{flex-wrap:wrap}header{align-items:start}header button{white-space:nowrap}}
</style>
